import pyperclip

players = ['Chris Woakes', 'Mark Chapman', 'Scott Edwards', 'Saud Shakeel', 'Mujeeb Ur Rahman', 'Mushfiqur Rahim', 'David Miller', 'Dushan Hemantha', 'Virat Kohli', 'David Warner', 'Jonny Bairstow', 'Trent Boult', 'Logan van Beek', 'Hasan Ali', 'Naveen-ul-Haq', 'Mustafizur Rahman', 'Keshav Maharaj', 'Pathum Nissanka', 'Hardik Pandya', 'Mitchell Starc', 'Mark Wood', 'Mitchell Santner', 'Bas de Leede', 'Mohammad Nawaz', 'Rahmat Shah', 'Mahmudullah', 'Rassie van der Dussen', 'Dilshan Madushanka', 'Rohit Sharma', 'Mitchell Marsh', 'Joe Root', 'Daryl Mitchell', 'Paul van Meekeren', 'Shadab Khan', 'Rahmanullah Gurbaz', 'Towhid Hridoy', 'Lungi Ngidi', 'Kasun Rajitha', 'Mohammed Siraj', 'Cameron Green', 'Liam Livingstone', 'Will Young', 'Roelof van der Merwe', 'Fakhar Zaman', 'Mohammad Nabi', 'Shakib Al Hasan', 'Kagiso Rabada', 'Matheesha Pathirana', 'Shreyas Iyer', 'Marnus Labuschagne', 'Harry Brook', 'Matt Henry', 'Saqib Zulfiqar', 'Babar Azam', 'Rashid Khan', 'Litton Das', 'Temba Bavuma', 'Sadeera Samarawickrama', 'Kuldeep Yadav', 'Adam Zampa', 'Moeen Ali', 'Tom Latham', 'Colin Ackermann', 'Haris Rauf', 'Fazalhaq Farooqi', 'Najmul Hossain Shanto', 'Aiden Markram', 'Kusal Mendis', 'Jasprit Bumrah', 'Glenn Maxwell', 'Sam Curran', 'Devon Conway', "Maxwell O'Dowd", 'Mohammad Rizwan', 'Najibullah Zadran', 'Mehidy Hasan Miraz', 'Gerald Coetzee', 'Dunith Wellalage', 'Ishan Kishan', 'Alex Carey', 'Jos Buttler', 'James Neesham', 'Anil Nidamanuru', 'Imam-ul-Haq', 'Hashmatullah Shahidi', 'Taskin Ahmed', 'Marco Jansen', 'Dhananjaya de Silva', 'Ravichandran Ashwin', 'Steve Smith', 'Dawid Malan', 'Glenn Phillips', 'Vikramjit Singh', 'Iftikhar Ahmed', 'Ibrahim Zadran', 'Shoriful Islam', 'Quinton de Kock', 'Kusal Perera', 'KL Rahul', 'Josh Hazlewood', 'Adil Rashid', 'Rachin Ravindra', 'Aryan Dutt', 'Shaheen Shah Afridi', 'Azmatullah Omarzai', 'Tanzid Hasan', 'Heinrich Klaasen', 'Charith Asalanka', 'Ravindra Jadeja', 'Pat Cummins', 'Reece Topley', 'Lockie Ferguson', 'Ryan Klein', 'Abdullah Shafique', 'Ikram Ali Khil', 'Mahedi Hasan', 'Tabraiz Shamsi', 'Maheesh Theekshana', 'Shardul Thakur', 'Marcus Stoinis', 'Gus Atkinson', 'Kane Williamson', 'Sybrand Engelbrecht', 'Agha Salman', 'Riaz Hassan', 'Hasan Mahmud', 'Reeza Hendricks', 'Dimuth Karunaratne', 'Shubman Gill', 'Josh Inglis', 'David Willey', 'Ish Sodhi', 'Shariz Ahmad', 'Mohammad Wasim', 'Noor Ahmad', 'Tanzim Hasan Sakib', 'Andile Phehlukwayo', 'Chamika Karunaratne', 'Mohammed Shami', 'Travis Head', 'Ben Stokes', 'Tim Southee', 'Wesley Barresi', 'Usama Mir', 'Abdul Rahman', 'Nasum Ahmed', 'Lizaad Williams', 'Lahiru Kumara', 'Suryakumar Yadav', 'Sean Abbott']

to_print = ''
for p in players[135:160]:
    p = p.split(" ")
    name = "+".join(p)

    a = f"https://www.google.com/search?q=site%3Ahttp%3A%2F%2Fwww.howstat.com%2Fcricket%2FStatistics%2FPlayers%2F+%22{name}%22&sca_esv=576019406&rlz=1C5GCEM_enUS1075US1075&ei=7WU3ZZujO6G0ptQP5aenyAc&ved=0ahUKEwjbzcn4iI6CAxUhmokEHeXTCXkQ4dUDCBA&uact=5&oq=site%3Ahttp%3A%2F%2Fwww.howstat.com%2Fcricket%2FStatistics%2FPlayers%2F+%22{name}%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiRXNpdGU6aHR0cDovL3d3dy5ob3dzdGF0LmNvbS9jcmlja2V0L1N0YXRpc3RpY3MvUGxheWVycy8gIlNlYW4gQWJib3R0IkjcEFDaDljaDnABeACQAQCYATqgATqqAQExuAEDyAEA-AEC-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp"

    b = f"https://www.google.com/search?q=site%3Acricbuzz.com%2Fprofiles+%22{name}%22&sca_esv=576019406&rlz=1C5GCEM_enUS1075US1075&ei=Z2U3Zc_2J5OiptQP2IOb6AQ&ved=0ahUKEwiPxsO4iI6CAxUTkYkEHdjBBk0Q4dUDCBA&uact=5&oq=site%3Acricbuzz.com%2Fprofiles+%22{name}%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiLHNpdGU6Y3JpY2J1enouY29tL3Byb2ZpbGVzICJBbmlsIE5pZGFtYW51cnUiSIhFUPs4WLhDcAJ4AJABAJgBSqABugKqAQE1uAEDyAEA-AEC-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp"

    to_print += f"""open '{a}' && open '{b}' && """

pyperclip.copy(to_print[:-3])